# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "buonny"
    ports: 
      - "15432:5432"
    networks:
      - cakepostgres

  adminer:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "buonny"
      PGADMIN_DEFAULT_PASSWORD: "buonny"
    depends_on:
      - db
    networks:
      - cakepostgres
networks:
  cakepostgres:
    driver: bridge